#include "pngparser.h"
#include <stdio.h>
#include <string.h>

// LibFuzzer stub
//
int LLVMFuzzerTestOneInput(const char *Data, size_t Size) {
  
  struct image *test_img;

  // We're now fuzzing the file name, not the actual file;
  // hence our test file itself should be valid: reuse one of our seeds

  // Null-terminate the input string; in order to do this, we have to
  // copy Data into a null-terminated char-array

  if (Size > 0) {

    char dest[Size];

    memset(dest, '\0', Size);

    for (int i = 0; i < (Size-1); i++) {
      dest[i] = Data[i];
    }

    // Open an empty buffer that has the name generated by the fuzzer
    FILE *file_to_load = fopen(dest, "w");

    // exit if load unsuccessful
    if (!file_to_load) return 0; 
     
    // Now open png file from seed directory
    FILE *image_to_copy = fopen("../seeds/palette.png", "r");

    // copy seed file byte by byte into the buffer with the 
    // fuzzer-generated name
    char current_char = 0;
    while ((current_char = fgetc(image_to_copy)) != EOF) {
      fputc(current_char, file_to_load);
    }

    // close the copied image and the copy of the image
    fclose(file_to_load);
    fclose(image_to_copy);

    // What would happen if we run multiple fuzzing processes at the same time?
    // Take a look at the name of the file.
    if (load_png(dest, &test_img) == 0)
      free(test_img);

  }

  // Always return 0
  return 0;
}